title: RF Signal Processing - Documentation
description: Documentation and media for the RF Signal Processing project.
baseurl: /rf-signal-processing
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
  - scope:
      path: "assets/audio"
    values:
      audio: true
  - scope:
      path: "assets/infographx"
    values:
      image: true
  - scope:
      path: "assets/pptx"
    values:
      presentation: true
  - scope:
      path: "assets/video"
    values:
      video: true